### ISSUE TITLE
This is not a issue

### ISSUE THREAD

**Issue by ecoli404** [arc298/instagram-scraper#291]
I love your app, and there are now some new media called Highlights. While looking up, I've found every media is contained over: "/stories/highlights", and I thing it could be easy to implement in your code, but I'm really new over this and I don't know what to do. Thanks!

**Comment by edgartaor** [comment]
Seem this already was sugested #261 .
But I don't know if there is a milestone for this feature.

**Comment by aaronraimist** [comment]
Duplicate of #147

**Comment by AlexNik** [comment]
Done in #481
