### ISSUE TITLE
Is there a way to get the account names or links to the actual instagram post when looking by hashtag?

### ISSUE THREAD

**Issue by natashamathur** [arc298/instagram-scraper#448]
Is there a way to get any identifying info for the photo, like the username or a link, when scraping by hashtag?

**Comment by gabrielmdu** [comment]
The link to the image is just `'https://instagram.com/p/' + shortcode`.

For the username I added a call to the method that fetches media details and inserted the username to the final item result, before being written to JSON, inside `__scrape_query`. Exactly like this:

```
details = self.__get_media_details(item['shortcode'])
item['username'] = details['owner']['username']
```

I just don't know if this could mess up the results when the scraper is executed for locations.
