### ISSUE TITLE
Ban and JSONDecodeError

### ISSUE THREAD

**Issue by FahmiRR** [arc298/instagram-scraper#482]
Hi, I have been trying to extract around 1000 accounts profile and media metadata for research purposes. I split the account list 100 per batch (so It generate 10 list file) to avoid ban. I try to put time.sleep() between each account (1-3s) and each batch (1-2min). Here is my implementation,

`python instagram-scraper.py --media-metadata --media_types none --destination xxx --profile-metadata --maximum 200 -f xxx_n.txt`

But after reaching the 4th file, I encounter this error code

`ERROR: Error getting user details for xxx. Please verify that the user exists.`

After changing my internet access, I can resume my fetch again. But I'm afraid it will get banned again in the future. Is there any way to avoid this??

I have tried to put proxies. Here is the implementation

`python instagram-scraper.py --media-metadata --media_types none --destination hasilscrape --profile-metadata --proxies '{"https":"https://xx.xx.xx.xx:xxxx"}' --maximum 200 -f xxx_n.txt`

But I encounter this error

`ERROR: Check is valid json type.
Traceback (most recent call last):
  File "metadatascraper_sleep.py", line 1407, in <module>
    main()
  File "metadatascraper_sleep.py", line 1376, in main
    scraper = InstagramScraper(**vars(args))
  File "metadatascraper_sleep.py", line 132, in __init__
    self.session.proxies = json.loads(self.proxies)
  File "C:\Program Files\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Anyone know how to solve this?

**Comment by HUMORCE** [comment]
type **Two** Double quotes in JSON string, when you are using PowerShell.

Example:
`--proxies '{""http"": ""http://localhost:port"", ""https"": ""https://localhost:port"" }'`

_Other escape characters also work, but this is the simplest._

**Comment by FahmiRR** [comment]
Hi sorry for the slow reply, it works wonderfully, thanks @HUMORCE

**Comment by FahmiRR** [comment]
Hi after changing the proxies new error come up

`python metadatascraper_sleep.py --media-metadata --media_types none --destination hasilscrape --profile-metadata --proxies '{""http"": ""http://xxx.xx.xx.xx:xxxx"", ""https"": ""https://xxx.xx.xx.xx:xxxx""}' --maximum 200 -f nama_ke_76.txt`

error

```
Traceback (most recent call last):
  File "metadatascraper_sleep.py", line 1407, in <module>
    main()
  File "metadatascraper_sleep.py", line 1352, in main
    raise ValueError('Must provide only one of the following: username(s) OR a filename containing username(s) OR --followings-input')
ValueError: Must provide only one of the following: username(s) OR a filename containing username(s) OR --followings-input
```

Any clue?

**Comment by HUMORCE** [comment]
which shell are you using?

**Comment by FahmiRR** [comment]
I am sorry I'm not familiar with the term, do you mean like shell as the command prompt on windows?

**Comment by HUMORCE** [comment]
yes, command prompt (cmd.exe) or powershell (powershell.exe).
which one?

**Comment by FahmiRR** [comment]
command prompt

**Comment by HUMORCE** [comment]
i tried same command in powershell and command prompt
work fine in powershell, 
same error in command prompt.

so, try switch to powershell.

**Comment by HUMORCE** [comment]
if you must to use command prompt, see:
`--proxies "{""http"": ""http://localhost:port"", ""https"": ""https://localhost:port"" }"`

note: use double quotes instead of single quotes for wrap json string.

**Comment by AlexNik** [comment]
Add debug output #732
Try to use the instagram-scraper with login credentials.
