### ISSUE TITLE
non following profiles (when providing <your username> and <password>

### ISSUE THREAD

**Issue by iArslan95** [arc298/instagram-scraper#515]
Hi, 
Thank you for this project! It is being very useful for me atm. 

I stumbled upon the following 'problem':
when providing my username and password and scraping a profile, which I do not follow BUT is public,  it returns the error "ERROR: Error getting user details for kemalbekci. Please verify that the user exists.".
When removing my username and password, this error does not appear and the scraper performs its task. 

This is unfortunate because I would like to scrape the profile picture in better resolution for profiles which I do not follow.

maybe this could be fixed by providing the option to follow profiles you input?

best, Ismail Arslan

**Comment by VasiliPupkin256** [comment]
Can you open it in a browser when you are logged in under this credentials? The user may have banned you.

**Comment by iArslan95** [comment]
Yes, I can open its profile so I am not blocked. Ive also tried this for other (public) profiles which I do not follow and the same problem occurs

**Comment by VasiliPupkin256** [comment]
It doesn't do this of course. I can scrape user kemalbekci from under my account credentials.

**Comment by iArslan95** [comment]
Perhaps you can try it with my account credentials:

!instagram-scraper uumutyalcn -u cupida_ai -p DivideetConquer30! -t image --maximum 1 --comments 

Also the maximum limit for items to scrape does not work for me. I might be using the code wrongly?

**Comment by VasiliPupkin256** [comment]
Interesting. Instagram doesn't return you any info about the user in its json code. Normally there should be field `entry_data` with lots of data related to the profile. But when I log in under your credentials instagram only returns this `"entry_data":{"ProfilePage":[{}]}`. Scraper heavily rely on this info and can't continue without it. It is not just instagram-scraper thing, instaloader also fails to fetch any data using your credentials. What is special about your profile?

**Comment by iArslan95** [comment]
Nothing should be special about my profile. I just created the account a few days ago. 

But also when using the scraper without my credentials: 
!instagram-scraper uumutyalcn -t image --maximum 1 --comment

this still provides me items which are non-image like videos and 10+ items. Altough, if I used the code correctly, I specified the scraper to only take images with a maximum of 1 item.

**Comment by VasiliPupkin256** [comment]
Not sure why `maximum` and `media_types` arguments aren't strict and I am not aware of this function so may be someone else would comment. Probably another issue should be opened for this other arguments related bug

**Comment by iArslan95** [comment]
Thanks for your responses.

I have trouble going through the codes for this scraper, its beyond my knowledge and experience. Whatsoever I will give it a shot to look at what might cause the problem.

**Comment by VasiliPupkin256** [comment]
And here we should learn what is wrong with your profile and why instagram disabled graphgl feature for it. Have you authorised it with email and/or phone, what emails does it send to you? What region or country have you registered it in, and do you use vpn or not?

**Comment by iArslan95** [comment]
I have authorised my account with mail. I am registered in the Netherlans and I do not use VPN

linked to the VPN thing: should I use one, also for preventing my IP getting banned?

**Comment by AlexNik** [comment]
I don't know is it the same issue or not.
I have "strange behaviour" of instagram site when i have opened 100+ tabs with different profiles in browser. Then I have "wait" issue but I can't open my own page too!
![Screenshot_2020-03-28 Page Not Found • Instagram](https://user-images.githubusercontent.com/941750/77862597-4bd79f00-7225-11ea-8c02-1d92d279856c.png)
If I open any profile in private tab (without credentials) there is no "wait".
After 30 seconds I could open any page but once. If I open one more I should wail 30 seconds.
Maybe it is the same issue or maybe not...

@iArslan95 Dou you have this issue with the specified profile or any?
Dou you try to scrape only one profile or many? How often?

**Comment by VasiliPupkin256** [comment]
It is hard to say when instagram bans ip or profile and why. Probably scraping from different profile through different vpn should be better than using the same ip, but the instagram ban heuristic is shady and unpredictable.
