### ISSUE TITLE
metadata not consistent with scraped data when using timestamp

### ISSUE THREAD

**Issue by Aaronzinhoo** [arc298/instagram-scraper#525]
It seems the metadata saved when using the arg `latest-stamp` seems to download all metadata and then check the metadata to see if the post is within the time stamp.

```
instagram-scraper --tag taeri_taeri --include-location --latest --latest-stamps timestamp.txt -d taeri_3_months
``` 
just want to make sure this is intended functionality or a bug. Either way, it can be improved it seems

**Comment by Aaronzinhoo** [comment]
I think we can change something around here to make sure the posts we add to the metadata are within the timestamp rather than just adding all of them

https://github.com/rarcega/instagram-scraper/blob/b8d6f5d31a73010f24ef19afba32c47a9ec1bf18/instagram_scraper/app.py#L490-L491

**Comment by Aaronzinhoo** [comment]
seems i was able to solve this problem with

```
                    if self.media_metadata or self.comments or
    self.include_location:
                         if self.latest_stamps_parser and
    self.initial_scraped_filemtime > self.__get_timestamp(item):
                             pass
                         else:
                             self.posts.append(item)
```

I will be making a PR later for this. But now there seems to be another problem I found. The metadata actually consists of copies (verified by comparing the id of the instagram post) and does not capture metadata for all images in the scraped. 

When you remove these copies, there is actually less metadata captured than images downloaded. I am wondering if this is an issue or not though, as maybe some posts have multiple images? I cannot verify directly unfortunately

**Comment by Aaronzinhoo** [comment]
I think the metadata should do one of two things; 

1. One metadata object per post (regardless of the amount of images that are within the post)
2. Every image downloaded gets one metadata object so that we have some sort of consistency here.

We can configure the metadata to produce both outcomes, I just wonder what others think is better

**Comment by arpitshah99-cpu** [comment]
@Aaronzinhoo thanks a lot. Your information is super helpful.
I am trying to download hashtag posts for a previous timeframe( like 6 months old data).
Can you please share the format for the file you included for "--latest-stamps timestamp.txt"?
You answer is much appreciated and thanks a lot for your original post.
