### ISSUE TITLE
instagram-scraper: command not found

### ISSUE THREAD

**Issue by nikhuji** [arc298/instagram-scraper#572]
Hello
after doing: pip3 install instagram-scraper
i tried to do a scrape, but got: 
instagram-scraper: command not found

i'm afraid i'm not knowledgable enough to know why i'm getting this message (on another computer i tried, by the way, it worked fine). is it because of python versions? 
i really hope you can help!

EDIT/ADDITION:
i think this may be to do with paths, but this is starting to get beyond my knowledge. if there are steps i can take, i can try to follow them. this looks like such a terrific script i'd love to get it working!

**Comment by eschwelgin** [comment]
try navigating to the proper folder and running 

$ sudo python setup.py install

**Comment by nikhuji** [comment]
Thanks. I solved it by using a virtual environment...

**Comment by Neuro-NX** [comment]
> Thanks. I solved it by using a virtual environment...

Please **"Close issue"** if your issue is resolved.
