### ISSUE TITLE
What is the example/format of a Timestamp file

### ISSUE THREAD

**Issue by TonyOuyangGit** [arc298/instagram-scraper#573]
In the program argument we can specify a file to indicate what is the latest timestamp we want to start searching. So I put --lateststamp=TimeStamp.txt, but what format of timestamp I should put in the txt? Any help would be appreciated, thank you!

**Comment by ekalin** [comment]
You don't need to specify anything, if the file doesn't exist it will be created. In the first run all media will be downloaded, then on subsequent runs only new media.

If you really want, the format is something like
```
[users]
username1 = 1597149810
username2 = 1597116752
```
where the values are [Unix epoch timestamps](https://en.wikipedia.org/wiki/Unix_time) corresponding to the timestamp of the last fetched media for each user.

**Comment by TonyOuyangGit** [comment]
Thanks so much, already addressed by @ekalin
