### ISSUE TITLE
Installed successfully, cant scrape accounts (MacOs)

### ISSUE THREAD

**Issue by Georgetown-creative** [arc298/instagram-scraper#612]
Hi everyone, I have installed instagram-scraper 1.9.1 successfully but when I run the next line for scraping it says command not found ($ instagram-scraper <username> -u <your username> -p <your password>) 

I have tried both with and without my username and password and still says that command not found

Any tips on how to troubleshoot why this message comes up?
-bash: instagram-scraper: command not found

Sorry for noob question, my first attempt at python.

<img width="754" alt="Screen Shot 2020-11-03 at 5 28 02 pm" src="https://user-images.githubusercontent.com/70085200/97969712-68f7d000-1dfb-11eb-80a2-484a172bb953.png">

**Comment by mshmandal** [comment]
sorry, I am not an expert. But I will give a try. If you have installed python in an environment, you need to navigate/activate that environment.  Then run the command instagram-scraper (if you have installed instagram-scraper there).

**Comment by AlexNik** [comment]
@Georgetown-creative how have you installed the app?

**Comment by Georgetown-creative** [comment]
I have uninstall and re-installed to show. Is it maybe due to these error messages about being on Path?

![Uploading Screen Shot 2020-11-06 at 8.47.11 am.png…]()

**Comment by mshmandal** [comment]
> @Georgetown-creative how have you installed the app?

I have installed in separate environment, so running from command line..

**Comment by mshmandal** [comment]
![Capture](https://user-images.githubusercontent.com/72704417/98316897-a1c3bf00-201e-11eb-90a1-ec4a0d071097.PNG)

**Comment by Georgetown-creative** [comment]
Thank you @mshmandal.

Can you please tell how to add to Path?

**Comment by AlexNik** [comment]
@Georgetown-creative try this one https://mrchens.github.io/2018/11/08/add-to-the-PATH-on-MAC/

**Comment by Georgetown-creative** [comment]
Thanks @AlexNik
