### ISSUE TITLE
RuntimeError with numpy

### ISSUE THREAD

**Issue by viktor02** [arc298/instagram-scraper#627]
I am getting runtime error when trying to start instagram-scraper
`RuntimeError: The current Numpy installation ('c:\\users\\user\\miniconda3\\envs\\insta\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86`

full log here https://pastebin.com/f4Rjp38R

**Comment by oferchen** [comment]
pip uninstall numpy

pip install numpy==1.19.3

**Comment by viktor02** [comment]
> 
> 
> pip uninstall numpy
> 
> pip install numpy==1.19.3

thanks, it works
