### ISSUE TITLE
Can it run in crontab? 

### ISSUE THREAD

**Issue by rosefun** [arc298/instagram-scraper#629]
I try to run it in `crontab -e`, so it can run everyday.

I use `crontab -`e to create a cron file, like

```
SHELL=/bin/sh
PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin
# Order of crontab fields
# minute        hour    mday    month   wday    command

09 12 * * * bash /data/project/run_crawl_ins.sh > /data/project/run_crawl_ins.log 2>&1
```

In the` run_crawl_ins.sh`, 

`instagram-scraper <username> -u <user> -p <password>  --latest`

I can run the ` run_crawl_ins.sh` correctly, but if I run it in crontab file,  an error  raises like,

`run_crawl_ins.sh: line 1: instagram-scraper: command not found`

**Comment by levi-turner** [comment]
`sudo find / -name instagram-scraper` Where is the binary located. Is it in `PATH`?

**Comment by rosefun** [comment]
Thanks! I find the full path by `which` , and use the full path instead of `instagram-scraper`.
