### ISSUE TITLE
moviepy was not found 

### ISSUE THREAD

**Issue by MohammadAnsari98** [arc298/instagram-scraper#631]
I'm using windows 10 and I cloned the project and used  `python setup.py install` for installing requirements, now when I run Instagram-scraper I get an error like this:

![Capture](https://user-images.githubusercontent.com/25693849/101079635-f9712e00-35bc-11eb-8bfe-3c8bf6e3893f.JPG)

**Comment by AlexNik** [comment]
@MohammadAnsari98 Have you had any errors during installation?

**Comment by aertist** [comment]
> @AlexNik nothing happened during `python setup.py install`

try this command `pip3 install moviepy`
