### ISSUE TITLE
Only mediadata for stories without downloading files

### ISSUE THREAD

**Issue by PC-Principal** [arc298/instagram-scraper#644]
Is there any method to save only stories mediadata without downloading files?

**Comment by AlexNik** [comment]
@PC-Principal what do you exatly mean by "metadata" of stories?

**Comment by PC-Principal** [comment]
> @PC-Principal what do you exatly mean by "metadata" of stories?

I mean that only generate json file with data about stories without downloading story sources,

--media-type none - saves only posts information, not stories data in this way.

**Comment by amedeobellodi** [comment]
> Is there any method to save only stories mediadata without downloading files?

I follow your request, since it'd be very useful to me as well.

**Comment by AlexNik** [comment]
Fix in #753
