### ISSUE TITLE
KeyError: "name='csrftoken', domain=None, path=None" - again

### ISSUE THREAD

**Issue by PC-Principal** [arc298/instagram-scraper#665]
Hello! There was a problem again when calling the script by: `instagram-scraper searched_user -u login -p pass --media-types story --media-metadata
`

Looks like this
`Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 11, in <module>
    load_entry_point('instagram-scraper==1.9.1', 'console_scripts', 'instagram-scraper')()
  File "/usr/local/lib/python3.6/site-packages/instagram_scraper/app.py", line 1607, in main
    scraper.authenticate_with_login()
  File "/usr/local/lib/python3.6/site-packages/instagram_scraper/app.py", line 255, in authenticate_with_login
    self.session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "/usr/local/lib/python3.6/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python3.6/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
`

Most likely in a day the script will work again, here it is obvious if there is some conflict with cookies, maybe there is some way to delete broken cookies?

**Comment by PC-Principal** [comment]
Solved - This issue can be avoided by using the cookiejar option. It will store the cookies of previous calls, if the cookies in this file are damaged - it will need to be deleted - the next time it is called, the file will be created again with working cookies. The cookiejar option will automatically recreate this file.

You also need to create some cooldowns between script calls or create a queue so as not to damage the cookies inside the file.

Example of calling script: `instagram-scraper username -u login -p pass --profile-metadata --media-types story --media-metadata --cookiejar /var/projects/pyscrap/coockies.txt`

**Comment by ellprrybil** [comment]
Hey, looks like I am facing the same issue. Here is my code and the response I got. 

url = 'https://www.instagram.com/accounts/login/'
url_main = url + 'ajax/'
auth = {'username': 'login', 'password': 'pass'}
headers = { 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36'}

with requests.Session() as s:
    response = s.get(url, headers=headers)
    headers['x-csrftoken'] = response.cookies['csrftoken']
    print(headers)

KeyError: "name='csrftoken', domain=None, path=None"

What I am trying to do is to connect to an Instagram account using requests. If you have any idea just let me know!
