### ISSUE TITLE
Example code please?

### ISSUE THREAD

**Issue by Aragorn-64** [arc298/instagram-scraper#686]
Hello, im not at all accustomed to using Python scraping tools etc. Could someone please give a working example of code (random login creds ofc) Im having lot of doubts like to use @ with the username or not? 

Also, if it is easier this way, could you correct what went wrong with **my command**:
_instagram-scraper --login-user @my_username --login-pass my_alpha_numeric_symbolheavy_password --media-metadata --media-types image video story @user_to_scrape_

**errors I get are:** 
_instagram-scraper: error: [Errno 2] No such file or directory: 'my username without @'
'my password' is not recognized as an internal or external command,
operable program or batch file._

Thanks a lot :)

**Comment by FatemeKhodayari** [comment]
Hi. 
To scrape any user, you can simply type `instagram-scraper username <username> -u <login_username> -p <login_password>`. This will create a directory named after the user you want to scrape and pull its posts, broadcasts and stories. You can also use the `instagram-scraper --help` command to see different commands and flags.

**Comment by brnmilk** [comment]
Its not working.

_SyntaxError: invalid syntax_
