### ISSUE TITLE
how to use --cookiejar

### ISSUE THREAD

**Issue by roncam82** [arc298/instagram-scraper#714]
Hi,

Im trying to use the --cookiejar so that there is no need to login every time to scrape. Can you help me on how to use it ?

I created an empty file and put the path to it: --cookiejar "path to file"

but getting the below error

![image](https://user-images.githubusercontent.com/46320963/129456897-8e1a6c55-41b3-47e9-a6b3-9a7adf33d44f.png)

thanks
regards

**Comment by AlexNik** [comment]
@roncam82 How do you run it?

**Comment by AlexNik** [comment]
@roncam82
The first run:
`instagram-scraper <profile1> -u <login> -p <password> -i --cookiejar cookies.jar`

The second run:
`instagram-scraper <profile2> --cookiejar cookies.jar`

**Comment by zv09** [comment]
so what is the point of using cookie here? 
as i just quickly examine part of code and what I got - am i right to say, script just save a session and run it again saved to use the same session on the further runs? 
is it can help to avoid locking and banning a parsing account from IG's servers side?

**Comment by AlexNik** [comment]
It works like regular cookies in browser - just saving you credentials for further runs without promting your login and password.
It does not protect you from banning because instagram bans accounts if it detects some suspicious activity like a lot of requests in the same time etc.
