### ISSUE TITLE
Return json metadata as variable

### ISSUE THREAD

**Issue by boerninator** [arc298/instagram-scraper#735]
Is it possible to return the metadata to a variable instead of exporting it as a json?

**Comment by AlexNik** [comment]
@boerninator could you describe it more detail?

**Comment by boerninator** [comment]
With the scraper it is very easy to return the metadata (post_URL, likes,  comments etc.) for a profile which is then saved as a '.json' file. I would like to use the scraper and return the dictionary with the metadata, so I can assign it to a variable, load it into pandas etc. without the workaround of first saving the json locally and reading it into pandas again. Is that somehow possible? I tried to assign x to "self._persist_metadata(dst, username)" in the 'scrape' function and it works kind of, but not really stable.

**Comment by AlexNik** [comment]
@boerninator see here
Is it ok for your purpose?
https://github.com/arc298/instagram-scraper/issues/630#issuecomment-951471713

**Comment by boerninator** [comment]
Thank you very much!!! @AlexNik

**Comment by boerninator** [comment]
Is it possible to use this as well with `scraper.authenticate_as_guest()` ? Because it works for me when using login credentials but not with guest login. There I get this error: 

> File "/Users/boer/opt/anaconda3/envs/lav/lib/python3.8/site-packages/instagram_scraper/app.py", line 928, in query_media_gen
>     media, end_cursor = self.__query_media(user['id'], end_cursor)
>   File "/Users/boer/opt/anaconda3/envs/lav/lib/python3.8/site-packages/instagram_scraper/app.py", line 952, in __query_media
>     payload = self._get_json(resp)['data']['user']
>   File "/Users/boer/opt/anaconda3/envs/lav/lib/python3.8/site-packages/instagram_scraper/app.py", line 159, in _get_json
>     return json.loads(text)
>   File "/Users/boer/opt/anaconda3/envs/lav/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/Users/boer/opt/anaconda3/envs/lav/lib/python3.8/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/Users/boer/opt/anaconda3/envs/lav/lib/python3.8/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AlexNik** [comment]
@boerninator I think no.
If you debug the response from Instagram it asks to login and redirect to login page.
Sometimes `scraper.authenticate_as_guest()` works but usually no and you should to login.

**Comment by zv09** [comment]
I watched when an error is issued and when not in this case, but not gone deeply to debug error in this case... 
Seems parsing as guest is possible if IG post shared publicly, if it is need to be a follower for appropriate user to parse it posts, then authenticated parsing mode is only possible...
