### ISSUE TITLE
What's the usage of latest stamps?

### ISSUE THREAD

**Issue by naziko2411** [arc298/instagram-scraper#738]
I don't exactly how latest stamps is. Is latest stamps is the usage of timestamps of the metadata of somewhat posts, stories and reels?

**Comment by AlexNik** [comment]
@naziko2411 No.
It uses timestamps of your runs.
If you've never scraped account data it scrape all posts.
Then if you scrape this account after 5 days it will download posts which have appeared in theese 5 days only.

**Comment by naziko2411** [comment]
Thanks, latest stamps actually means timestamp for running the application, I guess?

**Comment by AlexNik** [comment]
@naziko2411 yes

**Comment by naziko2411** [comment]
I think it's the only application that downloads everything, while using latest stamps? This helps me a lot

**Comment by AlexNik** [comment]
@naziko2411 could you close the issue if your questions is answered?

**Comment by naziko2411** [comment]
Yes.
