### ISSUE TITLE
How to download archive?

### ISSUE THREAD

**Issue by naziko2411** [arc298/instagram-scraper#740]
As I am aware, this project downloads everything on Instagram content. To download archives, should I use latest stamps?

**Comment by AlexNik** [comment]
Archives?
What do you mean?
If you mean posts with up to 10 slides it will donloaded as regular post -> just images or video?

**Comment by naziko2411** [comment]
Both regular and archived posts, like images and video.

**Comment by AlexNik** [comment]
If you want you cold use `--latest-stamps` 😃 
It will download both.
The difference is that without this option it download all posts evry run but with this option it download only new posts from your last run and don't redownload posts which have been downloaded already.

**Comment by naziko2411** [comment]
Thanks.
