### ISSUE TITLE
FIXED GRAPHQL ERROR FOR GOOD

### ISSUE THREAD

**Issue by novitae** [arc298/instagram-scraper#741]
i had this error as everyone "graphql error", and even with the update it wasn't working.
idk why it haven't been fixed before, it was pretty easy (for my usage, I didn't tried it with optional args and all)

the problem was that instagram was returning another api dictionary, with a completely different structure.

delete the code from the line `    def augment_node(self, node):` to `            self.logger.warning('Failed to get media details for ' + shortcode)`,
and replace it with the following:
```
    def augment_node(self, node):
        self.extract_tags(node)

        details = None
        if self.include_location and 'location' not in node:
            details = self.__get_media_details(node['shortcode'])
            node['location'] = details.get('location') if details else None

        if 'urls' not in node:
            node['urls'] = []
        if node['is_video'] and 'video_url' in node:
            node['urls'] = [node['video_url']]
        elif '__typename' in node and node['__typename'] == 'GraphImage':
            node['urls'] = [self.get_original_image(node['display_url'])]
        else:
            if details is None:
                details = self.__get_media_details(node['shortcode'])

            if details:
                if '__typename' in details and details['__typename'] == 'GraphVideo':
                    node['urls'] = [details['video_url']]
                elif '__typename' in details and details['__typename'] == 'GraphSidecar':
                    urls = []
                    for carousel_item in details['edge_sidecar_to_children']['edges']:
                        urls += self.augment_node(carousel_item['node'])['urls']
                    node['urls'] = urls
                else:
                    try:
                        node['urls'] = [self.get_original_image(details['display_url'])]
                    except (TypeError, KeyError):
                        pt1 = details['carousel_media']
                        node['urls'] = [pt1[e]['image_versions2']['candidates'][0]['url'] for e in range(len(pt1))]

        return node

    def __get_media_details(self, shortcode):
        resp = self.get_json(VIEW_MEDIA_URL.format(shortcode))

        if resp is not None:
            try:
                return self._get_json(resp)['graphql']['shortcode_media']
            except ValueError:
                # Response wasn't JSON, so maybe it was an HTML page.
                data = resp.split("window.__additionalDataLoaded(")[1].split("});</script>")[0].split('{"graphql":')[1]
                try:
                    return self._get_json(data)['shortcode_media']
                except ValueError:
                    self.logger.warning('Failed to get media details for ' + shortcode)
            except KeyError:
                return self._get_json(resp)['items'][0]

        else:
            self.logger.warning('Failed to get media details for ' + shortcode)
```

**Comment by novitae** [comment]
(btw, there's no informations of any type in this api response, idk where it comes from but I don't ask me too much questions, at least it works. if you want to see the response you get with this api when you get the graphql error, place after the `# Response wasn't JSON, so maybe it was an HTML page.` the following line:
```
open('path/to/export/the/file/fuckthisweirdapi.json', 'w').write(json.dumps(resp, indent=4))
```

**Comment by AlexNik** [comment]
@novitae You could create pull request by yourself.

**Comment by novitae** [comment]
> @novitae You could create pull request by yourself.

YEP

**Comment by LowKey22** [comment]
Hi if i may ask; I am trying the settings you suggested here and instead of the graphql error i then get the the 
KeyError: 'carousel_media'

Probably an easy failure im not used to? i didnt get it running it once yet.. maybe it is described already? sorry for asking! hope to get it working..

**Comment by novitae** [comment]
> Hi if i may ask; I am trying the settings you suggested here and instead of the graphql error i then get the the KeyError: 'carousel_media'
> 
> Probably an easy failure im not used to? i didnt get it running it once yet.. maybe it is described already? sorry for asking! hope to get it working..

Because @AlexNik deleted the `[0]` after the ['carousel_media'] (without knowing why because he never saw how the API json response that was causing the previous KeyError looks like) that was in the path of the important media to retrieve when he reviewed the file

**Comment by LowKey22** [comment]
okay thanks alot for the anwer! unfortunately adding it doesnt fix the error somehow.. mhmhh ^^ i wonder how others get it working though.. lel

**Comment by novitae** [comment]
> okay thanks alot for the anwer! unfortunately adding it doesnt fix the error somehow.. mhmhh ^^ i wonder how others get it working though.. lel

oh okay, im sorry I thought it would work ... I think this program definitely needs a full rebuilt to avoid all the new errors people are getting, I would loved to do it but I don't have the time at all

**Comment by kd-developer1** [comment]
Curious that this issue is affecting people at different times. If they have changed the API response JSON, you would think we all would have gotten the issue on the same day. I see that novitae posted this 2 months ago (Nov 16, 2021), but I just started to get the issue yesterday Jan 19, 2022.  Regardless, the fix works for me!!!

**Comment by novitae** [comment]
> Curious that this issue is affecting people at different times. If they have changed the API response JSON, you would think we all would have gotten the issue on the same day. I see that novitae posted this 2 months ago (Nov 16, 2021), but I just started to get the issue yesterday Jan 19, 2022. Regardless, the fix works for me!!!

Yes I know ... it is very weird. They didn't changed the API response, it is just another one different (probably in function of the time, the location, the users ...)
