### ISSUE TITLE
How to use in code

### ISSUE THREAD

**Issue by amirsasani** [arc298/instagram-scraper#766]
How can I use this in a python script?

**Comment by AlexNik** [comment]
@amirsasani https://github.com/arc298/instagram-scraper/issues/630#issuecomment-951471713

**Comment by AlexNik** [comment]
I've updated Readdme
https://github.com/arc298/instagram-scraper/blob/8d7b97f3d85c36c80bd98b548a0f07b51b05782b/README.md?plain=1#L197
