### ISSUE TITLE
best_candidate invalid logic

### ISSUE THREAD

**Issue by 89z** [arc298/instagram-scraper#770]
The current logic seems to just take the first result, or perhaps the item with the most height:

https://github.com/arc298/instagram-scraper/blob/1d0501813df1f846906c3ea69713577590acef08/instagram_scraper/app.py#L620-L624

However this doesnt work in call cases. For example if you look at ID `2667018861376986393`:

~~~json
"video_versions": [
   {
      "type": 101,
      "width": 720,
      "height": 720,
      "url": "https://scontent-hou1-1.cdninstagram.com/v/t50.2886-16/242437172_262241085905082_9146900263799630754_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjcyMC5mZWVkLmRlZmF1bHQifQ&_nc_ht=scontent-hou1-1.cdninstagram.com&_nc_cat=106&_nc_ohc=UNLGtnkmcA8AX_YvqIl&edm=ALQROFkBAAAA&vs=17904793547175654_2221242612&_nc_vs=HBksFQAYJEdEUk1jdzY2V01YQ2dlNEFBS0lydE50VFVmQl9ia1lMQUFBRhUAAsgBABUAGCRHSUVVY2c1R1J0X283aEVDQUJJY2dSb2RJZUk0YmtZTEFBQUYVAgLIAQAoABgAGwGIB3VzZV9vaWwBMBUAACb8uZGov9LdPxUCKAJDMywXQEMd0vGp%2B%2BcYEmRhc2hfYmFzZWxpbmVfMl92MREAdeoHAA%3D%3D&_nc_rid=ec61ea173f&ccb=7-4&oe=61FA00FF&oh=00_AT9Ed2x-KFOrwYC78jxPBIJKK6lCYxyh3vXddTYaDnnlLw&_nc_sid=30a2ef",
      "id": "17904793547175654v"
   }, {
      "type": 102,
      "width": 720,
      "height": 720,
      "url": "https://scontent-hou1-1.cdninstagram.com/v/t50.2886-16/242232307_279445243764790_1376057086795897231_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjcyMC5mZWVkLmRlZmF1bHQifQ&_nc_ht=scontent-hou1-1.cdninstagram.com&_nc_cat=110&_nc_ohc=jgNwkH72uwQAX-oSt7O&edm=ALQROFkBAAAA&vs=17938138630620599_2044314915&_nc_vs=HBksFQAYJEdQTXJjQTQySUgxcUotNEFBSS1aSURtaHZCZ1Ria1lMQUFBRhUAAsgBABUAGCRHSUVVY2c1R1J0X283aEVDQUJJY2dSb2RJZUk0YmtZTEFBQUYVAgLIAQAoABgAGwGIB3VzZV9vaWwBMBUAACb8uZGov9LdPxUCKAJDMywXQEMd0vGp%2B%2BcYEmRhc2hfYmFzZWxpbmVfMV92MREAdeoHAA%3D%3D&_nc_rid=ec61ea173f&ccb=7-4&oe=61FA6160&oh=00_AT_7ykTmPMNqdlmq0sqbT1m0fe67qUARYE7Ho3a3jjfCFg&_nc_sid=30a2ef",
      "id": "17938138630620599v"
   }, {
      "type": 103,
      "width": 720,
      "height": 720,
      "url": "https://scontent-hou1-1.cdninstagram.com/v/t50.2886-16/242232307_279445243764790_1376057086795897231_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjcyMC5mZWVkLmRlZmF1bHQifQ&_nc_ht=scontent-hou1-1.cdninstagram.com&_nc_cat=110&_nc_ohc=jgNwkH72uwQAX-oSt7O&edm=ALQROFkBAAAA&vs=17938138630620599_2044314915&_nc_vs=HBksFQAYJEdQTXJjQTQySUgxcUotNEFBSS1aSURtaHZCZ1Ria1lMQUFBRhUAAsgBABUAGCRHSUVVY2c1R1J0X283aEVDQUJJY2dSb2RJZUk0YmtZTEFBQUYVAgLIAQAoABgAGwGIB3VzZV9vaWwBMBUAACb8uZGov9LdPxUCKAJDMywXQEMd0vGp%2B%2BcYEmRhc2hfYmFzZWxpbmVfMV92MREAdeoHAA%3D%3D&_nc_rid=ec61ea173f&ccb=7-4&oe=61FA6160&oh=00_AT_7ykTmPMNqdlmq0sqbT1m0fe67qUARYE7Ho3a3jjfCFg&_nc_sid=30a2ef",
      "id": "17938138630620599v"
   }
],
~~~

All three items have the same height, and in fact two of them are actually the same URL. If you request the URLs, you will see that have different size:

~~~
HTTP/2 200
content-type: video/mp4
timing-allow-origin: *
x-fb-vts-requestid: 1b105c5a95
content-length: 2725256

HTTP/2 200
content-type: video/mp4
timing-allow-origin: *
x-fb-vts-requestid: B04848156C4F608
content-length: 1788966
~~~

This is what InstaLoader does:

https://github.com/instaloader/instaloader/blob/fdcf2e136767cfefab5abada9143c8882aea9d41/instaloader/structures.py#L396-L408

I dont know if thats the best option, but I think the current logic of Instagram-Scraper could be improved.

**Comment by AlexNik** [comment]
@nns33213 Could you see this issue?

**Comment by nns33213** [comment]
@89z @VasiliPupkin256 in InstaLoader they just ignore the `video_versions` metadata completely and make several HTTP HEAD requests for each URL to determine and download the version with the largest size (in OP's example 3 HEAD requests + 1 GET request but I've seen cases with a lot more).

This is a completely different approach to what we were discussing.

They implemented it here: https://github.com/instaloader/instaloader/pull/1232

Another suggested solution was to download the candidate with the max video type: https://github.com/instaloader/instaloader/issues/1022#issuecomment-879240895

**Comment by 89z** [comment]
I think I solved this. So if you just want to look at `video_versions`, you get this result:

~~~
Type:101 Width:720 Height:540 Bandwidth:211,754
Type:102 Width:720 Height:540 Bandwidth:541,145
Type:103 Width:720 Height:540 Bandwidth:541,145
~~~

So you dont need to make extra requests, just always get Type 102 or 103. Or you can look at `video_dash_manifest` you can get even better options:

~~~
Width:720 Height:540 Bandwidth:1,288,420
Width:720 Height:540 Bandwidth:541,145
Width:720 Height:540 Bandwidth:211,754
Width:490 Height:368 Bandwidth:90,571
~~~

**Comment by AlexNik** [comment]
@89z Is Any code changes needed?

**Comment by 89z** [comment]
Couple of more points. First, not all posts have `video_dash_manifest`, so you will need to fall back to `video_versions` in those cases. Also, I noticed that even with the posts that have `video_dash_manifest`, you have to request with a correct User-Agent. If you use wrong agent, you will get a normal response, but the `video_dash_manifest` will be missing. The detection is pretty strict, I have some sample code for the Android agent here:

https://github.com/89z/mech/blob/8fdab8dc/research/2022-02-01/bearer.go#L11-L54

**Comment by 89z** [comment]
I believe I have finished the logic for this, if it helps:

https://github.com/89z/mech/blob/v1.46.3/instagram/media.go#L37-L82

I also found out today, regarding images, that in some cases Instagram checks the resolution in the User-Agent. If the resolution is too low, then responses will not contain the higher quality images. Here is my current User-Agent that works:

~~~
Instagram 195.0.0.31.123 Android (99/9; 0; 9999x9999; brand; model; device; platform
~~~

**Comment by AlexNik** [comment]
@89z do you have one user aget for all queries?
Because login in this lib is proceed via Google Chrome UA
 https://github.com/arc298/instagram-scraper/blob/20e755e54a8fdf9f6b83fb2dc19e25ed3fe06305/instagram_scraper/constants.py#L4

**Comment by 89z** [comment]
I use the Android User-Agent for everything. This allows me to the `/api/v1/accounts/login/` for login as well:

https://github.com/89z/mech/blob/v1.46.3/instagram/login.go#L29-L58

**Comment by nns33213** [comment]
@AlexNik you can merge my branch. In commit https://github.com/nns33213/instagram-scraper/commit/6c1f3c5291245e872ffc391e8134dbae9d836792 I've copied the logic from InstaLoader. It makes several HEAD requests for each video and downloads the one with the biggest size.

**Comment by AlexNik** [comment]
@nns33213 Does the HEAD request decrease the limit of "good" queries?
I mean that if we send +3 HEAD queries per post, we could download the same count of posts until we recieve 429 error or 4 times less?

**Comment by nns33213** [comment]
@AlexNik those are CDN requests. They do not count towards any rate limit.

**Comment by AlexNik** [comment]
@afterdelight Did you change the user agent?

**Comment by nns33213** [comment]
> @[nns33213](https://github.com/nns33213) i still get lower resolution for photos from your branch

@afterdelight Okay, they must have changed something again because _photos_ not being the highest resolution in the first index is something new. Even InstaLoader assumes ['image_versions2']['candidates'][0] everywhere: https://github.com/instaloader/instaloader/blob/fdcf2e136767cfefab5abada9143c8882aea9d41/instaloader/structures.py#L1114

Try pulling my branch again: https://github.com/nns33213/instagram-scraper/commit/6cdd8468e02384b8e200b929f376448e3df9108e

**Comment by afterdelight** [comment]
> @afterdelight Did you change the user agent?

No, i didn't

> > @[nns33213](https://github.com/nns33213) i still get lower resolution for photos from your branch
> 
> @afterdelight Okay, they must have changed something again because _photos_ not being the highest resolution in the first index is something new. Even InstaLoader assumes ['image_versions2']['candidates'][0] everywhere: https://github.com/instaloader/instaloader/blob/fdcf2e136767cfefab5abada9143c8882aea9d41/instaloader/structures.py#L1114
> 
> Try pulling my branch again: [nns33213@6cdd846](https://github.com/nns33213/instagram-scraper/commit/6cdd8468e02384b8e200b929f376448e3df9108e)

Still get the same results.. got 750x750 instead of 1440xx1440

**Comment by nns33213** [comment]
> Still get the same results.. got 750x750 instead of 1440xx1440

Can't do much without a post/profile URL... Sometimes the higher version just isn't available.

**Comment by afterdelight** [comment]
well i meant i got 1440x1440 with instaloader, so there is a higher resolution available

**Comment by AlexNik** [comment]
It might be depend on user agent.
In this lig it is very old with lower resolution.
I'm going to update it this or next week.

**Comment by afterdelight** [comment]
okay, i will wait for the update
