### ISSUE TITLE
ERROR: Failed to get media details for CSW-I8uh4rZ

### ISSUE THREAD

**Issue by gudaocode** [arc298/instagram-scraper#786]
Searching rachellievava for posts: 0 media [00:00, ? media/s]ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CbQC3DcBRgE
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CbFw0uvBvsN
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for Ca92FyhB6Nt
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for Ca42ibVhHU3
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for Ca1GHBQBCjT
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for Cam3-vvhFBR
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for Cah0FmTBhFq
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CaU5ealh15X
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CaKflQphTLx
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CaFX2H4BNqL
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CaAJKE5JsFT
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CZj12zjBKZ6
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CZew8SZBNax
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CZUejfxhJ_e
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CZMwrZ5Bgyi
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CYrVCUPhqs0
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CYWk9xghC54
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CYRccXshvfQ
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CX_f0mdhkqN
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CXtXQdkBuJg
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CXgkDpNB_yi
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CXRFJjrBWCl
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CXLyJZBhtRO
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CW-x-1bhRp1
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CWvo7-uBPXO
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CWYTQW7BuC0
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CWGZeC8hEy3
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CV27rraBI5v
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CVk6oZrhTMy
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CVfv8X_BLbG
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CVdP6nHhquA
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CVLQ8Q-hg7-
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CVInAyph11S
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CU7wsoiBGZQ
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CUsOkX0Bo6q
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CUaTfELhatp
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CUNa49ahcee
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CUAfaRyhHWE
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CT4v8owh0ZX
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CTw1c11Bs1P
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CTkK4LzofBz
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CTfBKAfB0my
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CTND2wfBl81
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CTKhVKcBFXx
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CTFVxJ4BU4O
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CTARZulBg6V
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CS9V6GghjQU
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CSW-I8uh4rZ
ERROR: Please wait a few minutes before you try again.
ERROR: Failed to get media details for CRwW16cHod-
Searching rachellievava for posts: 11 media [00:18,  1.72s/ media]
Downloading: 100%|#####################################################################| 26/26 [00:01<00:00, 15.85it/s]

**Comment by VasiliPupkin256** [comment]
You've probably scraped too many profiles and your account hits rate limit. Do what it tells you, wait a few minutes before you try again.

**Comment by gudaocode** [comment]
Thank you！I
