### ISSUE TITLE
I need this program to be working asap pls :(

### ISSUE THREAD

**Issue by refatriana** [arc298/instagram-scraper#806]
i couldn't use this program pls help me
ive tried several times to install and uninstall it but it didn't change

I type 
`instagram-scraper bleacherreport`

or
`instagram-scraper bleacherreport u() -p() `

it always said:

> ERROR: getting user details for bleacherreport. Please verify that the user exists

I really need this program for my undergraduate thesis please help me :(

**Comment by AlexNik** [comment]
The Instagram has changed its behavior.
Wait for next release please.

**Comment by AlexNik** [comment]
Fixed in https://github.com/arc298/instagram-scraper/tree/v1.11.0
https://github.com/arc298/instagram-scraper/pull/809
