### ISSUE TITLE
Only download the first picture and ignore the following pictures in a single post

### ISSUE THREAD

**Issue by victoryy2003** [arc298/instagram-scraper#808]
The bot sometimes seems to only download the first picture, and ignore the following pictures in a single post

https://github.com/arc298/instagram-scraper/issues/633

**Comment by Raymon360** [comment]
> The bot sometimes seems to only download the first picture, and ignore the following pictures in a single post
> 
> #633

I have the same problem you are having

**Comment by victoryy2003** [comment]
> > The bot sometimes seems to only download the first picture, and ignore the following pictures in a single post
> > #633
> 
> I have the same problem you are having

https://github.com/arc298/instagram-scraper/issues/805#issuecomment-1146850656

**Comment by Raymon360** [comment]
> > > Bot sepertinya hanya mengunduh gambar pertama, dan melihat gambar berikut dalam satu postingan 
> > > #633
> > 
> > 
> > Saya memiliki masalah yang sama dengan yang Anda alami
> 
> [#805 (komentar)](https://github.com/arc298/instagram-scraper/issues/805#issuecomment-1146850656)

so what should i do to fix the problem? Have you found a solution for this problem?
Please tell me, how. I'm currently in research for computer vision, and I need an instagram scraper program to collect image data of a person
