### ISSUE TITLE
ERROR: Error getting user details. Please verify that the user exists.

### ISSUE THREAD

**Issue by djmarioka** [arc298/instagram-scraper#815]
Hi,

it's giving this **error again: "ERROR: Error getting user details. Please verify that the user exists."**, some days ago it stopped giving it, but 2 o 3 days ago, it's giving it out again:

![dfsdfsd](https://user-images.githubusercontent.com/81478245/173110464-afe68f77-7499-4c9e-ba63-cbd8cc0c6234.png)

Could you fix it?.

Thanks.

**Comment by Seeger0216** [comment]
same problem.i think instagram change something and this program can't use anymore until upgrade.

**Comment by AlexNik** [comment]
Fixed in https://github.com/arc298/instagram-scraper/tree/v1.11.0
https://github.com/arc298/instagram-scraper/pull/809
