### ISSUE TITLE
Login failed with {"authenticated": false}

### ISSUE THREAD

**Issue by poludu** [arc298/instagram-scraper#840]
OS：CentOS 7
instagram-scraper version: 1.10.6
The program works well before July 8, and then suddenly fails in downloading and prints the logs:

ERROR: Login failed for xxx
ERROR: {"user": true, "authenticated": false, "status": "ok"}

I could confirm that the account is OK and can log in Ins.

**Comment by akhepcat** [comment]
Confirmed for me as well:

    ERROR: Login failed for AB$USER
    ERROR: {"user": true, "authenticated": false, "status": "ok"}

**Comment by poludu** [comment]
Now I know why. The account is in the blacklists of Ins. It can log in web system but can't use in crawler. It's not the crawler's problem.

**Comment by akhepcat** [comment]
Hrm..  interesting, because my account isn't blacklisted, nor any of the accounts i test crawling with.   I can't get anything.
